export const SUPER_ADMIN_ROLE = 'super_admin';

export const PAGE_PERMISSIONS = {
  '/dashboard': 'dashboard.view',
  '/HRManagement': 'teachers.create',
  '/HRManagement?staffType=teacher': 'teachers.create',
  '/HRManagement?staffType=staff': 'staff.create',
  '/staff/list': 'staff.view',
  '/students/attendance-history/:id': 'attendance.history.view',

  '/class-management/Classes': 'classes.view',
  '/class-management/sections': 'sections.view',
  '/class-management/session': 'sessions.view',
  '/class-management/subjects': 'subjects.view',

  '/students/list': 'students.view',
  '/students/admission': 'students.create',
  '/students/create-id-card': 'students.id_card.view',
  '/students/parents': 'parents.view',
  '/students/parents/profile/:id': 'parents.view',
  '/students/attendance': 'attendance.view',
  '/students/class_asign': 'students.assign_class',
  '/students/schedule': 'students.schedule.view',
  '/students/fees': 'fees.view',
  '/students/profile/:id': 'students.profile.view',
  '/students/details/:id': 'fees.details.view',

  '/teachers/list': 'teachers.view',
  '/teachers/details/:id': 'teachers.details.view',
  '/teachers/salary-increments': 'teachers.salary_increments.view',
  '/teachers/attendance': 'teachers.attendance.view',
  '/teachers/attendance-history/:id': 'teachers.attendance.view',
  '/teachers/schedule': 'teachers.schedule.view',

  '/finance': 'finance.view',
  '/finance/setup/income-expence': 'finance.heads.view',
  '/finance/setup/expense-heads': 'finance.heads.view',
  '/finance/income/fund-collection': 'funds.create',
  '/finance/income/fund-list': 'funds.view',
  '/finance/expenses/payroll': 'salary.view',
  '/finance/other-income-expense': 'finance.transactions.view',
  '/finance/reports/financial-statements': 'finance.reports.view',

  '/hifz': 'hifz.view',
  '/hifz/daily/entry': 'hifz.daily.create',
  '/hifz/daily/list': 'hifz.daily.view',
  '/hifz/weekly/entry': 'hifz.weekly.create',
  '/hifz/weekly/list': 'hifz.weekly.view',
  '/hifz/monthly/entry': 'hifz.monthly.create',
  '/hifz/monthly/list': 'hifz.monthly.view',
  '/hifz/para/entry': 'hifz.para.create',
  '/hifz/para/list': 'hifz.para.view',

  '/exams/schedule-list': 'exams.view',
  '/exams/schedule': 'exams.create',
  '/exams/result-list': 'exam_results.view',
  '/exams/result': 'exam_results.create',
  '/exams/result-grades': 'result_grades.view',

  '/store': 'store.view',
  '/store/dashboard': 'store.view',
  '/store/approvals': 'store.approve',
  '/store/categories': 'store.categories.view',
  '/store/damaged-stock': 'store.damaged_stock.view',
  '/store/items': 'store.items.view',
  '/store/purchases': 'store.purchases.view',
  '/store/reports': 'store.reports',
  '/store/stock-issues': 'store.stock_issues.view',
  '/store/returns': 'store.returns.view',
  '/store/suppliers': 'store.suppliers.view',
  '/store/suppliers/:supplierId': 'store.suppliers.view',
  '/store/units': 'store.units.view',

  '/setting/shift': 'settings.shifts.view',
  '/setting/department': 'settings.departments.view',
  '/setting/degree-name': 'settings.degrees.view',
  '/Profile/setting': 'profile.view',
  '/Profile/change-password': 'profile.change_password',
  '/Profile/cities': 'settings.cities.view',
  '/Profile/support': 'support.view',
  '/Profile/suggestions': 'suggestions.view',

  '/role-management': 'role_management.view',
  '/role-management/create': 'roles.create',
  '/role-management/:roleId': 'roles.view',
  '/role-management/:roleId/edit': 'roles.edit',
  '/role-management/users': 'users.view',
  '/role-management/users/create': 'users.create',
  '/role-management/users/:userId': 'users.view',
  '/role-management/users/:userId/edit': 'users.edit',
};

export const ROLE_PERMISSION_MODULES = [
  {
    id: 'dashboard',
    label: 'ڈیش بورڈ',
    permissions: [
      { key: 'dashboard.view', name: 'ڈیش بورڈ دیکھیں' },
    ],
  },
  {
    id: 'role_management',
    label: 'کردار مینجمنٹ',
    permissions: [
      { key: 'role_management.view', name: 'کردار مینجمنٹ دیکھیں' },
      { key: 'roles.view', name: 'کردار دیکھیں' },
      { key: 'roles.create', name: 'کردار بنائیں' },
      { key: 'roles.edit', name: 'کردار میں ترمیم کریں' },
      { key: 'roles.delete', name: 'کردار حذف کریں' },
      { key: 'roles.assign_permissions', name: 'کردار کو اجازتیں دیں' },
    ],
  },
  {
    id: 'users',
    label: 'صارفین',
    permissions: [
      { key: 'users.view', name: 'صارفین دیکھیں' },
      { key: 'users.create', name: 'صارف بنائیں' },
      { key: 'users.edit', name: 'صارف میں ترمیم کریں' },
      { key: 'users.delete', name: 'صارف حذف کریں' },
    ],
  },
  {
    id: 'students',
    label: 'طلباء',
    permissions: [
      { key: 'students.view', name: 'طلباء دیکھیں' },
      { key: 'students.create', name: 'طالب علم شامل کریں' },
      { key: 'students.edit', name: 'طالب علم میں ترمیم کریں' },
      { key: 'students.delete', name: 'طالب علم حذف کریں' },
      { key: 'students.profile.view', name: 'طالب علم پروفائل دیکھیں' },
      { key: 'students.id_card.view', name: 'آئی ڈی کارڈ دیکھیں' },
      { key: 'students.assign_class', name: 'کلاس تفویض کریں' },
      { key: 'students.schedule.view', name: 'طلباء شیڈول دیکھیں' },
    ],
  },
  {
    id: 'parents_attendance',
    label: 'والدین اور حاضری',
    permissions: [
      { key: 'parents.view', name: 'والدین دیکھیں' },
      { key: 'parents.create', name: 'والدین شامل کریں' },
      { key: 'parents.edit', name: 'والدین میں ترمیم کریں' },
      { key: 'parents.delete', name: 'والدین حذف کریں' },
      { key: 'attendance.view', name: 'حاضری دیکھیں' },
      { key: 'attendance.create', name: 'حاضری درج کریں' },
      { key: 'attendance.edit', name: 'حاضری میں ترمیم کریں' },
      { key: 'attendance.history.view', name: 'حاضری تاریخ دیکھیں' },
    ],
  },
  {
    id: 'teachers_staff',
    label: 'اساتذہ اور عملہ',
    permissions: [
      { key: 'teachers.view', name: 'اساتذہ دیکھیں' },
      { key: 'teachers.create', name: 'استاد شامل کریں' },
      { key: 'teachers.edit', name: 'استاد میں ترمیم کریں' },
      { key: 'teachers.delete', name: 'استاد حذف کریں' },
      { key: 'teachers.details.view', name: 'استاد تفصیل دیکھیں' },
      { key: 'teachers.attendance.view', name: 'اساتذہ حاضری دیکھیں' },
      { key: 'teachers.schedule.view', name: 'اساتذہ شیڈول دیکھیں' },
      { key: 'teachers.salary_increments.view', name: 'تنخواہ انکریمنٹ دیکھیں' },
      { key: 'staff.view', name: 'عملہ دیکھیں' },
      { key: 'staff.create', name: 'عملہ شامل کریں' },
      { key: 'staff.edit', name: 'عملہ میں ترمیم کریں' },
      { key: 'staff.delete', name: 'عملہ حذف کریں' },
    ],
  },
  {
    id: 'class_management',
    label: 'کلاس مینجمنٹ',
    permissions: [
      { key: 'classes.view', name: 'جماعتیں دیکھیں' },
      { key: 'classes.create', name: 'جماعت بنائیں' },
      { key: 'classes.edit', name: 'جماعت میں ترمیم کریں' },
      { key: 'classes.delete', name: 'جماعت حذف کریں' },
      { key: 'sections.view', name: 'سیکشن دیکھیں' },
      { key: 'sections.create', name: 'سیکشن بنائیں' },
      { key: 'sections.edit', name: 'سیکشن میں ترمیم کریں' },
      { key: 'sections.delete', name: 'سیکشن حذف کریں' },
      { key: 'sessions.view', name: 'سیشن دیکھیں' },
      { key: 'subjects.view', name: 'مضامین دیکھیں' },
    ],
  },
  {
    id: 'finance',
    label: 'مالیات',
    permissions: [
      { key: 'finance.view', name: 'مالیات دیکھیں' },
      { key: 'finance.heads.view', name: 'آمدن و خرچ سیٹ اپ دیکھیں' },
      { key: 'finance.transactions.view', name: 'آمدن و خرچ اندراج دیکھیں' },
      { key: 'finance.transactions.create', name: 'آمدن و خرچ درج کریں' },
      { key: 'finance.reports.view', name: 'مالی رپورٹس دیکھیں' },
      { key: 'funds.view', name: 'عطیات دیکھیں' },
      { key: 'funds.create', name: 'عطیہ درج کریں' },
      { key: 'funds.edit', name: 'عطیہ میں ترمیم کریں' },
      { key: 'funds.delete', name: 'عطیہ حذف کریں' },
      { key: 'fees.view', name: 'فیس دیکھیں' },
      { key: 'fees.create', name: 'فیس بنائیں' },
      { key: 'fees.edit', name: 'فیس میں ترمیم کریں' },
      { key: 'fees.delete', name: 'فیس حذف کریں' },
      { key: 'fees.details.view', name: 'فیس تفصیل دیکھیں' },
      { key: 'salary.view', name: 'تنخواہ دیکھیں' },
      { key: 'salary.create', name: 'تنخواہ بنائیں' },
      { key: 'salary.edit', name: 'تنخواہ میں ترمیم کریں' },
      { key: 'salary.delete', name: 'تنخواہ حذف کریں' },
    ],
  },
  {
    id: 'hifz_exams',
    label: 'حفظ اور امتحانات',
    permissions: [
      { key: 'hifz.view', name: 'حفظ دیکھیں' },
      { key: 'hifz.daily.view', name: 'یومیہ جائزہ دیکھیں' },
      { key: 'hifz.daily.create', name: 'یومیہ جائزہ درج کریں' },
      { key: 'hifz.weekly.view', name: 'ہفتہ وار جائزہ دیکھیں' },
      { key: 'hifz.weekly.create', name: 'ہفتہ وار جائزہ درج کریں' },
      { key: 'hifz.monthly.view', name: 'ماہانہ جائزہ دیکھیں' },
      { key: 'hifz.monthly.create', name: 'ماہانہ جائزہ درج کریں' },
      { key: 'hifz.para.view', name: 'پارہ جائزہ دیکھیں' },
      { key: 'hifz.para.create', name: 'پارہ جائزہ درج کریں' },
      { key: 'exams.view', name: 'امتحانات دیکھیں' },
      { key: 'exams.create', name: 'امتحان بنائیں' },
      { key: 'exams.edit', name: 'امتحان میں ترمیم کریں' },
      { key: 'exams.delete', name: 'امتحان حذف کریں' },
      { key: 'exam_results.view', name: 'نتائج دیکھیں' },
      { key: 'exam_results.create', name: 'نتیجہ درج کریں' },
      { key: 'result_grades.view', name: 'نتیجہ گریڈ دیکھیں' },
    ],
  },
  {
    id: 'store',
    label: 'اسٹور',
    permissions: [
      { key: 'store.view', name: 'اسٹور دیکھیں' },
      { key: 'store.approve', name: 'اسٹور منظوری دیں' },
      { key: 'store.items.view', name: 'اشیاء دیکھیں' },
      { key: 'store.items.create', name: 'شے شامل کریں' },
      { key: 'store.items.edit', name: 'شے میں ترمیم کریں' },
      { key: 'store.items.delete', name: 'شے حذف کریں' },
      { key: 'store.purchases.view', name: 'خریداری دیکھیں' },
      { key: 'store.purchases.create', name: 'خریداری درج کریں' },
      { key: 'store.stock_issues.view', name: 'اسٹاک اجرا دیکھیں' },
      { key: 'store.returns.view', name: 'واپسی دیکھیں' },
      { key: 'store.damaged_stock.view', name: 'خراب اسٹاک دیکھیں' },
      { key: 'store.reports', name: 'اسٹور رپورٹس دیکھیں' },
      { key: 'store.suppliers.view', name: 'سپلائرز دیکھیں' },
      { key: 'store.categories.view', name: 'کیٹیگریز دیکھیں' },
      { key: 'store.units.view', name: 'اکائیاں دیکھیں' },
    ],
  },
  {
    id: 'settings',
    label: 'ترتیبات',
    permissions: [
      { key: 'settings.shifts.view', name: 'شفٹ دیکھیں' },
      { key: 'settings.shifts.create', name: 'شفٹ بنائیں' },
      { key: 'settings.departments.view', name: 'شعبہ جات دیکھیں' },
      { key: 'settings.departments.create', name: 'شعبہ بنائیں' },
      { key: 'settings.degrees.view', name: 'اسناد دیکھیں' },
      { key: 'settings.cities.view', name: 'شہر دیکھیں' },
      { key: 'profile.view', name: 'پروفائل دیکھیں' },
      { key: 'profile.change_password', name: 'پاس ورڈ تبدیل کریں' },
      { key: 'support.view', name: 'سپورٹ دیکھیں' },
      { key: 'suggestions.view', name: 'تجاویز دیکھیں' },
      { key: 'reports.view', name: 'رپورٹس دیکھیں' },
    ],
  },
];

export const getPagePermission = (path) => {
  if (!path) return null;

  const normalizedPath = path.split('?')[0];

  return PAGE_PERMISSIONS[path] || PAGE_PERMISSIONS[normalizedPath] || null;
};
